import { useEffect, useRef, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { EmptyState, Tag } from "../components/ui";
import { Icon } from "../components/icons";
import { Frame } from "./Frame";
import { api } from "../services/api";
import { Markdown } from "../components/Markdown";
import { sfx } from "../services/sound";

interface Source { title: string; url: string; snippet: string; }
type Phase = "idle" | "searching" | "found" | "analyzing" | "synthesizing" | "result";

const PHASE_LABEL: Record<Phase, string> = {
  idle: "", searching: "SEARCHING", found: "SOURCES FOUND", analyzing: "ANALYZING", synthesizing: "SYNTHESIZING", result: "RESULT",
};

export function Web() {
  const [query, setQuery] = useState("");
  const [phase, setPhase] = useState<Phase>("idle");
  const [sources, setSources] = useState<Source[]>([]);
  const [report, setReport] = useState("");
  const [demo, setDemo] = useState(false);
  const timers = useRef<number[]>([]);

  useEffect(() => () => { timers.current.forEach(clearTimeout); }, []);

  const synthesize = (srcs: Source[]) => {
    const intro = `## Research synthesis: "${query}"\n\nBased on ${srcs.length} source${srcs.length === 1 ? "" : "s"}:`;
    const bullets = srcs.map((s) => `- **${s.title.replace(/ \(DEMO\)$/, "")}** — ${s.snippet}`).join("\n");
    setReport(`${intro}\n\n${bullets}\n\n### Key takeaways\n\n${srcs.slice(0, 2).map((s) => `- ${s.snippet.split(".")[0]}.`).join("\n")}\n\n> Synthesis generated by the JARVIS research engine.`);
  };

  const run = async () => {
    if (!query.trim()) return;
    sfx.send();
    setPhase("searching"); setSources([]); setReport("");
    timers.current.forEach(clearTimeout);
    const step = (p: Phase, ms: number) => { timers.current.push(window.setTimeout(() => setPhase(p), ms)); };
    try {
      const r = await api.search(query.trim());
      const srcs: Source[] = Array.isArray(r.data) ? r.data : [];
      setDemo(Boolean(r.demo));
      setSources(srcs);
      step("found", 250);
      step("analyzing", 1300);
      step("synthesizing", 2400);
      timers.current.push(window.setTimeout(() => { synthesize(srcs); setPhase("result"); sfx.success(); }, 3400));
    } catch (e) {
      setPhase("idle");
      setReport(`> Search failed: ${(e as Error).message}`);
    }
  };

  return (
    <Frame icon="web" title="WEB RESEARCH CENTER" subtitle="Search → Sources → Analyze → Synthesize → Report">
      <div className="mb-4 flex gap-2">
        <input value={query} onChange={(e) => setQuery(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter") run(); }} placeholder="Research any topic…" className="input" aria-label="Research query" />
        <button onClick={run} className="btn-primary !px-4" aria-label="Search"><Icon name="search" size={15} /></button>
      </div>

      {/* Pipeline indicator */}
      <div className="mb-4 flex flex-wrap items-center gap-2">
        {(["searching", "found", "analyzing", "synthesizing", "result"] as Phase[]).map((p, i) => {
          const reached = phase === "result" || ["searching", "found", "analyzing", "synthesizing"].indexOf(phase) >= i;
          const current = phase === p;
          return (
            <div key={p} className="flex items-center gap-2">
              <span className={`tech-text text-[9px] tracking-[0.18em] ${current ? "text-cyan-300 animate-pulse" : reached ? "text-mut" : "text-dim/40"}`}>
                {PHASE_LABEL[p]}
              </span>
              {i < 4 && <Icon name="activity" size={10} className="text-dim/40" />}
            </div>
          );
        })}
        {demo && phase === "result" && <Tag tone="amber">DEMO SOURCES — configure a search API key for live results</Tag>}
      </div>

      <div className="grid grid-cols-1 gap-3 lg:grid-cols-2">
        <div className="space-y-2">
          <AnimatePresence>
            {sources.length === 0 && phase === "idle" && (
              <EmptyState icon="globe" title="ENTER A QUERY TO BEGIN" hint="JARVIS will search, read sources, and synthesize a structured report." />
            )}
            {sources.map((s, i) => (
              <motion.a
                key={i}
                href={s.url}
                target="_blank"
                rel="noreferrer"
                initial={{ opacity: 0, x: -12 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: i * 0.08 }}
                className="glass-soft block rounded-lg border border-white/10 p-3 transition-all hover:border-cyan-400/30"
              >
                <div className="flex items-start justify-between gap-2">
                  <p className="text-sm text-ink">{s.title}</p>
                  <Icon name="web" size={13} className="mt-0.5 shrink-0 text-dim" />
                </div>
                <p className="mt-1 line-clamp-3 text-xs text-dim">{s.snippet}</p>
                <p className="tech-text mt-1.5 truncate text-[9px] tracking-[0.1em] text-cyan-300/60">{s.url}</p>
              </motion.a>
            ))}
          </AnimatePresence>
        </div>

        <div className="glass-soft rounded-lg border border-white/10 p-4">
          <p className="tech-text mb-2 text-[10px] tracking-[0.25em] text-mut">SYNTHESIZED REPORT</p>
          {report ? (
            <Markdown>{report}</Markdown>
          ) : (
            <EmptyState icon="activity" title="AWAITING SYNTHESIS" hint="The final report will appear here once sources are analyzed." />
          )}
        </div>
      </div>
    </Frame>
  );
}
